### ISSUE TITLE
What theming_meta.xml for?

### ISSUE THREAD

**Issue by tsurumi-yizhou** [TrainerSnow/oneui-DreamDary#82]
Could I fetch OneUI's colorScheme through which?

**Comment by SimonBumiller** [comment]
Hey,

I'm not sure what you are asking about 😅.

The `theming_meta.xml` is used to direct the dynamic color scheme from the dynamic color feature of some newer android versions to the one ui color scheme used by the oneui-lib. It needs to be included because it is required by the `oui-compose` lib (also by me).

However, this forwarding does not work reliably and is hard to predict. This is why currently it is switched off by the call to `OneUiTheme` in the main app composable. You could try to change the `dynamicColor` boolean arg to true (default false).

If it works you can also start a pull request :)

**Comment by TrainerSnow** [comment]
Hey,

I'm not sure what you are asking about 😅.

The `theming_meta.xml` is used to direct the dynamic color scheme from the dynamic color feature of some newer android versions to the material-theme color scheme. It needs to be included because it is required by the `oui-compose` lib (also by me).

However, this forwarding does not work reliably and is hard to predict. This is why currently it is switched off by the call to `OneUiTheme` in the main app composable. You could try to change the `dynamicColor` boolean arg to true (default false).

If it works you can also start a pull request :)

**Comment by tsurumi-yizhou** [comment]
I'm implementing some oneui style components in my app, so I wonder how to adapt the system color.

I have decompiled the oneui app download from my phone and checked the res dictionary. I've also seen the oneui-compose library by you. It seems helpful, though without updates for a long time, it cannt be imported into my project. The target sdk version problem, I believe.

**Comment by tsurumi-yizhou** [comment]
Ok, I totally copy it from SamsungMessages and it doesn't work. Maybe I should create an issue in OneUI-Project.
